name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --no-cache --file Dockerfile --tag registry.nussi.net/adt:${{ github.sha }}
    - name: Push the Docker image tag
      run: docker push registry.nussi.net/adt:${{ github.sha }}
      
  push-latest:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v3
    - name: Pull the Docker image latest
      run:  docker pull registry.nussi.net/adt:${{ github.sha }}
    - name: Tag the Docker image latest
      run:  docker tag registry.nussi.net/adt:${{ github.sha }} registry.nussi.net/adt:latest
    - name: Push the Docker image latest
      run: docker push registry.nussi.net/adt:latest

      
  prune-images:
    runs-on: ubuntu-latest
    needs: 
    - build-and-push
    - push-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prune all the Docker images
      run: docker image prune --alll --force
      
