name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --no-cache --file Dockerfile --tag registry.nussi.net/adt:${{ github.sha }}
      
  push-sha:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Push the Docker image tag
      run: docker push registry.nussi.net/adt:${{ github.sha }}

  push-latest:
    runs-on: self-hosted
    needs: 
    - push-sha
    - build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Tag the Dockerr image latest
      run: docker tag registry.nussi.net/adt:${{ github.sha }} registry.nussi.net/adt:latest
    - name: Push the Docker image latest
      run: docker push registry.nussi.net/adt:latest
  
  prune:
    runs-on: self-hosted
    needs: 
    - push-sha
    - push-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prune all the Docker images
      run: docker image prune --all --force
