name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --no-cache --file Dockerfile --tag registry.nussi.net/adt:${{ github.sha }}
    - name: Push the Docker image tag
      run: docker push registry.nussi.net/adt:${{ github.sha }}
    - name: Push the Docker image latest
      run: if [ "$GITHUB_REF_NAME" == "main" ]; then docker push registry.nussi.net/adt:latest && docker tag registry.nussi.net/adt:${{ github.sha }} registry.nussi.net/adt:latest; else echo "Not main branch! Skipping pushing latest..."; fi
    - name: Prune all the Docker images
      run: docker image prune --alll --force
      
