name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  select-runner:
    runs-on: self-hosted
    outputs:
     RUNNER: ${{ runner.name }}
    steps:
      - run: echo "selected runner ${{ runner.name }}"
      
  build:
    needs: select-runner
    runs-on: ${{needs.select-runner.outputs.RUNNER}}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --no-cache --file Dockerfile --tag registry.nussi.net/adt:${{ github.sha }}
      
  push-sha:
    needs: 
    - build
    - select-runner
    runs-on: ${{needs.select-runner.outputs.RUNNER}}
    steps:
    - uses: actions/checkout@v3
    - name: Push the Docker image tag
      run: docker push registry.nussi.net/adt:${{ github.sha }}

  push-latest:
    needs: 
    - push-sha
    - build
    - select-runner
    runs-on: ${{needs.select-runner.outputs.RUNNER}}
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Tag the Dockerr image latest
      run: docker tag registry.nussi.net/adt:${{ github.sha }} registry.nussi.net/adt:latest
    - name: Push the Docker image latest
      run: docker push registry.nussi.net/adt:latest
  
  prune:
    needs: 
    - push-sha
    - push-latest
    - select-runner
    runs-on: ${{needs.select-runner.outputs.RUNNER}}
    steps:
    - uses: actions/checkout@v3
    - name: Prune all the Docker images
      run: docker image prune --all --force --filter label=storage="github_action_prune"
