name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag danussi/adt:${{ github.sha }}
    - name: Run the Docker image
      run: docker run danussi/adt:${{ github.sha }}
    
